In [11]:
import pandas as pd

df = pd.read_csv("d1.csv")
df.head()

,bulb_number,timestamp,power_consumption (Watts),voltage_levels (Volts),current_fluctuations (Amperes),temperature (Celsius),environmental_conditions,current_fluctuations_env (Amperes),fault_type
0,1,2023-09-06 07:53:23,106.18,238.52,6.127984,21.97,Rainy,0.780000,1.0
1,1,2023-03-28 16:28:29,58.71,235.99,3.010000,24.16,Clear,0.100000,0.0
2,1,2023-09-20 19:17:46,195.49,234.97,1.060000,13.64,Rainy,0.920000,0.0
3,1,2023-02-03 18:19:43,95.64,225.74,2.160000,15.82,Rainy,3.060000,0.0
4,1,2023-01-12 13:43:48,70.92,218.76,1.830000,19.12,Rainy,6.529021,4.0

In [12]:
df = df[df['fault_type'].isin([0,1])]
df['fault_type'].unique()

array([1., 0.])

In [16]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [17]:
df['timestamp'] = df['timestamp'].dt.time
df[['timestamp']].head()

  timestamp
0  07:53:23
1  16:28:29
2  19:17:46
3  18:19:43
7  08:26:19

In [18]:
df = df.drop('bulb_number', axis=1)

In [19]:
df.head()

,timestamp,power_consumption (Watts),voltage_levels (Volts),current_fluctuations (Amperes),temperature (Celsius),environmental_conditions,current_fluctuations_env (Amperes),fault_type
0,07:53:23,106.18,238.52,6.127984,21.97,Rainy,0.78,1.0
1,16:28:29,58.71,235.99,3.010000,24.16,Clear,0.10,0.0
2,19:17:46,195.49,234.97,1.060000,13.64,Rainy,0.92,0.0
3,18:19:43,95.64,225.74,2.160000,15.82,Rainy,3.06,0.0
7,08:26:19,116.02,213.66,2.480000,10.69,Clear,4.55,0.0

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['environmental_conditions'] = le.fit_transform(df['environmental_conditions'])

In [21]:
df.head()

,timestamp,power_consumption (Watts),voltage_levels (Volts),current_fluctuations (Amperes),temperature (Celsius),environmental_conditions,current_fluctuations_env (Amperes),fault_type
0,07:53:23,106.18,238.52,6.127984,21.97,2,0.78,1.0
1,16:28:29,58.71,235.99,3.010000,24.16,0,0.10,0.0
2,19:17:46,195.49,234.97,1.060000,13.64,2,0.92,0.0
3,18:19:43,95.64,225.74,2.160000,15.82,2,3.06,0.0
7,08:26:19,116.02,213.66,2.480000,10.69,0,4.55,0.0

In [22]:
df.isnull().sum()

timestamp                             0
power_consumption (Watts)             0
voltage_levels (Volts)                0
current_fluctuations (Amperes)        0
temperature (Celsius)                 0
environmental_conditions              0
current_fluctuations_env (Amperes)    0
fault_type                            0
dtype: int64

In [24]:
y = df['fault_type']

X = df.drop('fault_type', axis=1)

In [25]:
X['timestamp'] = pd.to_datetime(X['timestamp'].astype(str)).dt.hour

/tmp/ipykernel_210/4078941459.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  X['timestamp'] = pd.to_datetime(X['timestamp'].astype(str)).dt.hour

In [26]:
X['timestamp'].head()

0     7
1    16
2    19
3    18
7     8
Name: timestamp, dtype: int32

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(9712, 7)
(2429, 7)

In [30]:
clean_df = pd.concat([X, y], axis=1)

clean_df.to_csv("clean_streetlight_dataset.csv", index=False)